databaseChangeLog:
  - include:
      file: ./changelog/v1_create_new_schema_store.sql
      relativeToChangeLogFile: true
  - include:
      file: ./changelog/v2_create_user_table.sql
      relativeToChangeLogFile: true
  - include:
      file: ./changelog/v3_create_product_table.sql
      relativeToChangeLogFile: true
  - include:
      file: ./changelog/v4_create_bill_table.sql
      relativeToChangeLogFile: true
